/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AlertsResponse {
  active?: boolean;
  alertType?: 'DIP' | 'RISE';
  createdAt?: string;
  id?: number;
  notificationChannel?: 'EMAIL' | 'WHATSAPP' | 'BOTH';
  threshold?: number;
  ticker?: string;
}
