/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StockPriceResponse {
  datetime?: string;
  exchange?: string;
  name?: string;
  price?: string;
  symbol?: string;
}
