/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StockPriceRequest } from '../../models/stock-price-request';
import { StockPriceResponse } from '../../models/stock-price-response';

export interface GetStockPrice$Params {
      body: StockPriceRequest
}

export function getStockPrice(http: HttpClient, rootUrl: string, params: GetStockPrice$Params, context?: HttpContext): Observable<StrictHttpResponse<StockPriceResponse>> {
  const rb = new RequestBuilder(rootUrl, getStockPrice.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StockPriceResponse>;
    })
  );
}

getStockPrice.PATH = '/stocks/price';
