/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AlertsRequest } from '../../models/alerts-request';
import { AlertsResponse } from '../../models/alerts-response';

export interface CreateAlert$Params {
      body: AlertsRequest
}

export function createAlert(http: HttpClient, rootUrl: string, params: CreateAlert$Params, context?: HttpContext): Observable<StrictHttpResponse<AlertsResponse>> {
  const rb = new RequestBuilder(rootUrl, createAlert.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AlertsResponse>;
    })
  );
}

createAlert.PATH = '/alerts';
