/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AlertsResponse } from '../models/alerts-response';
import { createAlert } from '../fn/alerts-controller/create-alert';
import { CreateAlert$Params } from '../fn/alerts-controller/create-alert';
import { deleteAlert } from '../fn/alerts-controller/delete-alert';
import { DeleteAlert$Params } from '../fn/alerts-controller/delete-alert';
import { getUserAlerts } from '../fn/alerts-controller/get-user-alerts';
import { GetUserAlerts$Params } from '../fn/alerts-controller/get-user-alerts';
import { toggleAlert } from '../fn/alerts-controller/toggle-alert';
import { ToggleAlert$Params } from '../fn/alerts-controller/toggle-alert';

@Injectable({ providedIn: 'root' })
export class AlertsControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  static readonly GetUserAlertsPath = '/alerts';

  getUserAlerts$Response(params?: GetUserAlerts$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AlertsResponse>>> {
    return getUserAlerts(this.http, this.rootUrl, params, context);
  }

  getUserAlerts(params?: GetUserAlerts$Params, context?: HttpContext): Observable<Array<AlertsResponse>> {
    return this.getUserAlerts$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<AlertsResponse>>): Array<AlertsResponse> => r.body)
    );
  }

  static readonly CreateAlertPath = '/alerts';

  createAlert$Response(params: CreateAlert$Params, context?: HttpContext): Observable<StrictHttpResponse<AlertsResponse>> {
    return createAlert(this.http, this.rootUrl, params, context);
  }

  createAlert(params: CreateAlert$Params, context?: HttpContext): Observable<AlertsResponse> {
    return this.createAlert$Response(params, context).pipe(
      map((r: StrictHttpResponse<AlertsResponse>): AlertsResponse => r.body)
    );
  }

  static readonly ToggleAlertPath = '/alerts/{id}/toggle';

  toggleAlert$Response(params: ToggleAlert$Params, context?: HttpContext): Observable<StrictHttpResponse<AlertsResponse>> {
    return toggleAlert(this.http, this.rootUrl, params, context);
  }

  toggleAlert(params: ToggleAlert$Params, context?: HttpContext): Observable<AlertsResponse> {
    return this.toggleAlert$Response(params, context).pipe(
      map((r: StrictHttpResponse<AlertsResponse>): AlertsResponse => r.body)
    );
  }

  static readonly DeleteAlertPath = '/alerts/{id}';

  deleteAlert$Response(params: DeleteAlert$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteAlert(this.http, this.rootUrl, params, context);
  }

  deleteAlert(params: DeleteAlert$Params, context?: HttpContext): Observable<void> {
    return this.deleteAlert$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }
}