/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getStockPrice } from '../fn/stock-price-controller/get-stock-price';
import { GetStockPrice$Params } from '../fn/stock-price-controller/get-stock-price';
import { StockPriceResponse } from '../models/stock-price-response';

@Injectable({ providedIn: 'root' })
export class StockPriceControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  static readonly GetStockPricePath = '/stocks/price';

  getStockPrice$Response(params: GetStockPrice$Params, context?: HttpContext): Observable<StrictHttpResponse<StockPriceResponse>> {
    return getStockPrice(this.http, this.rootUrl, params, context);
  }

  getStockPrice(params: GetStockPrice$Params, context?: HttpContext): Observable<StockPriceResponse> {
    return this.getStockPrice$Response(params, context).pipe(
      map((r: StrictHttpResponse<StockPriceResponse>): StockPriceResponse => r.body)
    );
  }
}